# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DLmodel_all.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(219, 464)
        MainWindow.setStyleSheet("QWidget#centralwidget{ background-color: qlineargradient(spread:pad, x1:0.776577, y1:0.057, x2:1, y2:0.756, stop:0 rgba(34, 49, 63, 255), stop:1 rgba(64, 94, 120, 255));\n"
"}\n"
"\n"
"QPushButton,QComboBox{ background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0.94, y2:0.937, stop:0 rgba(65, 94, 121, 255), stop:0.20398 rgba(255, 255, 255, 255), stop:0.850746 rgba(255, 255, 255, 255), stop:1 rgba(71, 102, 131, 255));\n"
"font: 75 8.5pt \"Sitka Small\";\n"
"}\n"
"\n"
"QLabel{ color: rgb(255, 255, 255) }\n"
"\n"
"font: 75 8pt \"Sitka Small\";\n"
"  \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.model_page = QtWidgets.QWidget()
        self.model_page.setObjectName("model_page")
        self.model_gridLayout = QtWidgets.QGridLayout(self.model_page)
        self.model_gridLayout.setObjectName("model_gridLayout")
        self.model_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.model_verticalLayout_1.setSpacing(10)
        self.model_verticalLayout_1.setObjectName("model_verticalLayout_1")
        self.model_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.model_verticalLayout_2.setObjectName("model_verticalLayout_2")
        self.modelName_label = QtWidgets.QLabel(self.model_page)
        self.modelName_label.setObjectName("modelName_label")
        self.model_verticalLayout_2.addWidget(self.modelName_label, 0, QtCore.Qt.AlignHCenter)
        self.modelName_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.modelName_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.modelName_lineEdit.setMaximumSize(QtCore.QSize(125, 22))
        self.modelName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.modelName_lineEdit.setObjectName("modelName_lineEdit")
        self.model_verticalLayout_2.addWidget(self.modelName_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.model_verticalLayout_1.addLayout(self.model_verticalLayout_2)
        self.model_line_1 = QtWidgets.QFrame(self.model_page)
        self.model_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.model_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_line_1.setObjectName("model_line_1")
        self.model_verticalLayout_1.addWidget(self.model_line_1)
        self.model_horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_1.setObjectName("model_horizontalLayout_1")
        self.cnn_label = QtWidgets.QLabel(self.model_page)
        self.cnn_label.setMinimumSize(QtCore.QSize(50, 22))
        self.cnn_label.setMaximumSize(QtCore.QSize(100, 25))
        self.cnn_label.setObjectName("cnn_label")
        self.model_horizontalLayout_1.addWidget(self.cnn_label)
        self.cnn_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.cnn_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.cnn_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.cnn_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cnn_lineEdit.setObjectName("cnn_lineEdit")
        self.model_horizontalLayout_1.addWidget(self.cnn_lineEdit)
        self.model_verticalLayout_1.addLayout(self.model_horizontalLayout_1)
        self.model_line_2 = QtWidgets.QFrame(self.model_page)
        self.model_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.model_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_line_2.setObjectName("model_line_2")
        self.model_verticalLayout_1.addWidget(self.model_line_2)
        self.model_verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.model_verticalLayout_3.setObjectName("model_verticalLayout_3")
        self.inputSize_label = QtWidgets.QLabel(self.model_page)
        self.inputSize_label.setObjectName("inputSize_label")
        self.model_verticalLayout_3.addWidget(self.inputSize_label, 0, QtCore.Qt.AlignHCenter)
        self.model_horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_5.setSpacing(15)
        self.model_horizontalLayout_5.setObjectName("model_horizontalLayout_5")
        self.model_horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_6.setSpacing(0)
        self.model_horizontalLayout_6.setObjectName("model_horizontalLayout_6")
        self.height_label = QtWidgets.QLabel(self.model_page)
        self.height_label.setMinimumSize(QtCore.QSize(22, 22))
        self.height_label.setMaximumSize(QtCore.QSize(25, 22))
        self.height_label.setObjectName("height_label")
        self.model_horizontalLayout_6.addWidget(self.height_label, 0, QtCore.Qt.AlignRight)
        self.height_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.height_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.height_lineEdit.setMaximumSize(QtCore.QSize(35, 22))
        self.height_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.height_lineEdit.setObjectName("height_lineEdit")
        self.model_horizontalLayout_6.addWidget(self.height_lineEdit)
        self.model_horizontalLayout_5.addLayout(self.model_horizontalLayout_6)
        self.model_horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_7.setSpacing(0)
        self.model_horizontalLayout_7.setObjectName("model_horizontalLayout_7")
        self.width_label = QtWidgets.QLabel(self.model_page)
        self.width_label.setMinimumSize(QtCore.QSize(22, 22))
        self.width_label.setMaximumSize(QtCore.QSize(25, 22))
        self.width_label.setObjectName("width_label")
        self.model_horizontalLayout_7.addWidget(self.width_label, 0, QtCore.Qt.AlignRight)
        self.width_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.width_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.width_lineEdit.setMaximumSize(QtCore.QSize(35, 22))
        self.width_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.width_lineEdit.setObjectName("width_lineEdit")
        self.model_horizontalLayout_7.addWidget(self.width_lineEdit)
        self.model_horizontalLayout_5.addLayout(self.model_horizontalLayout_7)
        self.model_horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_8.setSpacing(0)
        self.model_horizontalLayout_8.setObjectName("model_horizontalLayout_8")
        self.channels_label = QtWidgets.QLabel(self.model_page)
        self.channels_label.setMinimumSize(QtCore.QSize(22, 22))
        self.channels_label.setMaximumSize(QtCore.QSize(25, 22))
        self.channels_label.setObjectName("channels_label")
        self.model_horizontalLayout_8.addWidget(self.channels_label, 0, QtCore.Qt.AlignRight)
        self.channels_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.channels_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.channels_lineEdit.setMaximumSize(QtCore.QSize(35, 22))
        self.channels_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.channels_lineEdit.setObjectName("channels_lineEdit")
        self.model_horizontalLayout_8.addWidget(self.channels_lineEdit)
        self.model_horizontalLayout_5.addLayout(self.model_horizontalLayout_8)
        self.model_verticalLayout_3.addLayout(self.model_horizontalLayout_5)
        self.model_verticalLayout_1.addLayout(self.model_verticalLayout_3)
        self.model_line_3 = QtWidgets.QFrame(self.model_page)
        self.model_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.model_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_line_3.setObjectName("model_line_3")
        self.model_verticalLayout_1.addWidget(self.model_line_3)
        self.model_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_2.setObjectName("model_horizontalLayout_2")
        self.model_verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.model_verticalLayout_4.setObjectName("model_verticalLayout_4")
        self.dense_label = QtWidgets.QLabel(self.model_page)
        self.dense_label.setMinimumSize(QtCore.QSize(50, 22))
        self.dense_label.setMaximumSize(QtCore.QSize(100, 25))
        self.dense_label.setObjectName("dense_label")
        self.model_verticalLayout_4.addWidget(self.dense_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.dense_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.dense_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.dense_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.dense_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dense_lineEdit.setObjectName("dense_lineEdit")
        self.model_verticalLayout_4.addWidget(self.dense_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.model_horizontalLayout_2.addLayout(self.model_verticalLayout_4)
        self.model_line_5 = QtWidgets.QFrame(self.model_page)
        self.model_line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.model_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_line_5.setObjectName("model_line_5")
        self.model_horizontalLayout_2.addWidget(self.model_line_5)
        self.model_verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.model_verticalLayout_5.setObjectName("model_verticalLayout_5")
        self.classes_label = QtWidgets.QLabel(self.model_page)
        self.classes_label.setMinimumSize(QtCore.QSize(50, 22))
        self.classes_label.setMaximumSize(QtCore.QSize(100, 25))
        self.classes_label.setObjectName("classes_label")
        self.model_verticalLayout_5.addWidget(self.classes_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.classes_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.classes_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.classes_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.classes_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.classes_lineEdit.setObjectName("classes_lineEdit")
        self.model_verticalLayout_5.addWidget(self.classes_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.model_horizontalLayout_2.addLayout(self.model_verticalLayout_5)
        self.model_verticalLayout_1.addLayout(self.model_horizontalLayout_2)
        self.model_line_4 = QtWidgets.QFrame(self.model_page)
        self.model_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.model_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_line_4.setObjectName("model_line_4")
        self.model_verticalLayout_1.addWidget(self.model_line_4)
        self.model_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_3.setObjectName("model_horizontalLayout_3")
        self.lstm_label = QtWidgets.QLabel(self.model_page)
        self.lstm_label.setMinimumSize(QtCore.QSize(50, 22))
        self.lstm_label.setMaximumSize(QtCore.QSize(100, 25))
        self.lstm_label.setObjectName("lstm_label")
        self.model_horizontalLayout_3.addWidget(self.lstm_label)
        self.lstm_lineEdit = QtWidgets.QLineEdit(self.model_page)
        self.lstm_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.lstm_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.lstm_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lstm_lineEdit.setObjectName("lstm_lineEdit")
        self.model_horizontalLayout_3.addWidget(self.lstm_lineEdit)
        self.model_verticalLayout_1.addLayout(self.model_horizontalLayout_3)
        self.model_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.model_horizontalLayout_4.setObjectName("model_horizontalLayout_4")
        self.reset_pushButton = QtWidgets.QPushButton(self.model_page)
        self.reset_pushButton.setStyleSheet("")
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.model_horizontalLayout_4.addWidget(self.reset_pushButton)
        self.initialize_pushButton = QtWidgets.QPushButton(self.model_page)
        self.initialize_pushButton.setObjectName("initialize_pushButton")
        self.model_horizontalLayout_4.addWidget(self.initialize_pushButton)
        self.model_verticalLayout_1.addLayout(self.model_horizontalLayout_4)
        self.model_gridLayout.addLayout(self.model_verticalLayout_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.model_page)
        self.cnn_page = QtWidgets.QWidget()
        self.cnn_page.setObjectName("cnn_page")
        self.cnn_gridLayout = QtWidgets.QGridLayout(self.cnn_page)
        self.cnn_gridLayout.setObjectName("cnn_gridLayout")
        self.cnn_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_1.setSpacing(10)
        self.cnn_verticalLayout_1.setObjectName("cnn_verticalLayout_1")
        self.cnn_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_2.setObjectName("cnn_verticalLayout_2")
        self.cnnName_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnName_label.setObjectName("cnnName_label")
        self.cnn_verticalLayout_2.addWidget(self.cnnName_label, 0, QtCore.Qt.AlignHCenter)
        self.cnnName_lineEdit = QtWidgets.QLineEdit(self.cnn_page)
        self.cnnName_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnName_lineEdit.setMaximumSize(QtCore.QSize(125, 22))
        self.cnnName_lineEdit.setText("")
        self.cnnName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnName_lineEdit.setObjectName("cnnName_lineEdit")
        self.cnn_verticalLayout_2.addWidget(self.cnnName_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.cnn_verticalLayout_1.addLayout(self.cnn_verticalLayout_2)
        self.cnn_line_1 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_1.setObjectName("cnn_line_1")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_1)
        self.cnn_horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_1.setObjectName("cnn_horizontalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_1.addItem(spacerItem)
        self.filters_label = QtWidgets.QLabel(self.cnn_page)
        self.filters_label.setMinimumSize(QtCore.QSize(50, 22))
        self.filters_label.setMaximumSize(QtCore.QSize(125, 25))
        self.filters_label.setObjectName("filters_label")
        self.cnn_horizontalLayout_1.addWidget(self.filters_label, 0, QtCore.Qt.AlignHCenter)
        self.filters_lineEdit = QtWidgets.QLineEdit(self.cnn_page)
        self.filters_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.filters_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.filters_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.filters_lineEdit.setObjectName("filters_lineEdit")
        self.cnn_horizontalLayout_1.addWidget(self.filters_lineEdit, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_1.addItem(spacerItem1)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_1)
        self.cnn_line_2 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_2.setObjectName("cnn_line_2")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_2)
        self.cnn_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_2.setSpacing(10)
        self.cnn_horizontalLayout_2.setObjectName("cnn_horizontalLayout_2")
        self.cnn_verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_3.setObjectName("cnn_verticalLayout_3")
        self.cnnKernel_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnKernel_label.setMinimumSize(QtCore.QSize(70, 22))
        self.cnnKernel_label.setMaximumSize(QtCore.QSize(70, 22))
        self.cnnKernel_label.setObjectName("cnnKernel_label")
        self.cnn_verticalLayout_3.addWidget(self.cnnKernel_label, 0, QtCore.Qt.AlignHCenter)
        self.cnn_horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_7.setSpacing(0)
        self.cnn_horizontalLayout_7.setObjectName("cnn_horizontalLayout_7")
        self.cnnKernel_lineEdit_1 = QtWidgets.QLineEdit(self.cnn_page)
        self.cnnKernel_lineEdit_1.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnKernel_lineEdit_1.setMaximumSize(QtCore.QSize(30, 22))
        self.cnnKernel_lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnKernel_lineEdit_1.setObjectName("cnnKernel_lineEdit_1")
        self.cnn_horizontalLayout_7.addWidget(self.cnnKernel_lineEdit_1, 0, QtCore.Qt.AlignHCenter)
        self.cnnKernelx_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnKernelx_label.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnKernelx_label.setMaximumSize(QtCore.QSize(25, 22))
        self.cnnKernelx_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnKernelx_label.setObjectName("cnnKernelx_label")
        self.cnn_horizontalLayout_7.addWidget(self.cnnKernelx_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.cnnKernel_lineEdit_2 = QtWidgets.QLineEdit(self.cnn_page)
        self.cnnKernel_lineEdit_2.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnKernel_lineEdit_2.setMaximumSize(QtCore.QSize(30, 22))
        self.cnnKernel_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnKernel_lineEdit_2.setObjectName("cnnKernel_lineEdit_2")
        self.cnn_horizontalLayout_7.addWidget(self.cnnKernel_lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.cnn_verticalLayout_3.addLayout(self.cnn_horizontalLayout_7)
        self.cnn_horizontalLayout_2.addLayout(self.cnn_verticalLayout_3)
        self.cnn_line_6 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.cnn_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_6.setObjectName("cnn_line_6")
        self.cnn_horizontalLayout_2.addWidget(self.cnn_line_6)
        self.cnn_verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_4.setObjectName("cnn_verticalLayout_4")
        self.cnnStride_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnStride_label.setMinimumSize(QtCore.QSize(70, 22))
        self.cnnStride_label.setMaximumSize(QtCore.QSize(70, 22))
        self.cnnStride_label.setObjectName("cnnStride_label")
        self.cnn_verticalLayout_4.addWidget(self.cnnStride_label, 0, QtCore.Qt.AlignHCenter)
        self.cnn_horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_8.setSpacing(0)
        self.cnn_horizontalLayout_8.setObjectName("cnn_horizontalLayout_8")
        self.cnnStride_lineEdit_1 = QtWidgets.QLineEdit(self.cnn_page)
        self.cnnStride_lineEdit_1.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnStride_lineEdit_1.setMaximumSize(QtCore.QSize(30, 22))
        self.cnnStride_lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnStride_lineEdit_1.setObjectName("cnnStride_lineEdit_1")
        self.cnn_horizontalLayout_8.addWidget(self.cnnStride_lineEdit_1, 0, QtCore.Qt.AlignHCenter)
        self.cnnStridex_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnStridex_label.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnStridex_label.setMaximumSize(QtCore.QSize(25, 22))
        self.cnnStridex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnStridex_label.setObjectName("cnnStridex_label")
        self.cnn_horizontalLayout_8.addWidget(self.cnnStridex_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.cnnStride_lineEdit_2 = QtWidgets.QLineEdit(self.cnn_page)
        self.cnnStride_lineEdit_2.setMinimumSize(QtCore.QSize(22, 22))
        self.cnnStride_lineEdit_2.setMaximumSize(QtCore.QSize(30, 22))
        self.cnnStride_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cnnStride_lineEdit_2.setObjectName("cnnStride_lineEdit_2")
        self.cnn_horizontalLayout_8.addWidget(self.cnnStride_lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.cnn_verticalLayout_4.addLayout(self.cnn_horizontalLayout_8)
        self.cnn_horizontalLayout_2.addLayout(self.cnn_verticalLayout_4)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_2)
        self.cnn_line_3 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_3.setObjectName("cnn_line_3")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_3)
        self.cnn_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_3.setSpacing(10)
        self.cnn_horizontalLayout_3.setObjectName("cnn_horizontalLayout_3")
        self.cnn_verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_5.setObjectName("cnn_verticalLayout_5")
        self.maxpKernel_label = QtWidgets.QLabel(self.cnn_page)
        self.maxpKernel_label.setMinimumSize(QtCore.QSize(70, 22))
        self.maxpKernel_label.setMaximumSize(QtCore.QSize(70, 22))
        self.maxpKernel_label.setObjectName("maxpKernel_label")
        self.cnn_verticalLayout_5.addWidget(self.maxpKernel_label, 0, QtCore.Qt.AlignHCenter)
        self.cnn_horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_9.setSpacing(0)
        self.cnn_horizontalLayout_9.setObjectName("cnn_horizontalLayout_9")
        self.maxpKernel_lineEdit_1 = QtWidgets.QLineEdit(self.cnn_page)
        self.maxpKernel_lineEdit_1.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpKernel_lineEdit_1.setMaximumSize(QtCore.QSize(30, 22))
        self.maxpKernel_lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpKernel_lineEdit_1.setObjectName("maxpKernel_lineEdit_1")
        self.cnn_horizontalLayout_9.addWidget(self.maxpKernel_lineEdit_1, 0, QtCore.Qt.AlignHCenter)
        self.maxpKernelx_label = QtWidgets.QLabel(self.cnn_page)
        self.maxpKernelx_label.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpKernelx_label.setMaximumSize(QtCore.QSize(25, 22))
        self.maxpKernelx_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpKernelx_label.setObjectName("maxpKernelx_label")
        self.cnn_horizontalLayout_9.addWidget(self.maxpKernelx_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.maxpKernel_lineEdit_2 = QtWidgets.QLineEdit(self.cnn_page)
        self.maxpKernel_lineEdit_2.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpKernel_lineEdit_2.setMaximumSize(QtCore.QSize(30, 22))
        self.maxpKernel_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpKernel_lineEdit_2.setObjectName("maxpKernel_lineEdit_2")
        self.cnn_horizontalLayout_9.addWidget(self.maxpKernel_lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.cnn_verticalLayout_5.addLayout(self.cnn_horizontalLayout_9)
        self.cnn_horizontalLayout_3.addLayout(self.cnn_verticalLayout_5)
        self.cnn_line_7 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.cnn_line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_7.setObjectName("cnn_line_7")
        self.cnn_horizontalLayout_3.addWidget(self.cnn_line_7)
        self.cnn_verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.cnn_verticalLayout_6.setObjectName("cnn_verticalLayout_6")
        self.maxpStride_label = QtWidgets.QLabel(self.cnn_page)
        self.maxpStride_label.setMinimumSize(QtCore.QSize(70, 22))
        self.maxpStride_label.setMaximumSize(QtCore.QSize(70, 22))
        self.maxpStride_label.setObjectName("maxpStride_label")
        self.cnn_verticalLayout_6.addWidget(self.maxpStride_label, 0, QtCore.Qt.AlignHCenter)
        self.cnn_horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_10.setSpacing(0)
        self.cnn_horizontalLayout_10.setObjectName("cnn_horizontalLayout_10")
        self.maxpStride_lineEdit_1 = QtWidgets.QLineEdit(self.cnn_page)
        self.maxpStride_lineEdit_1.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpStride_lineEdit_1.setMaximumSize(QtCore.QSize(30, 22))
        self.maxpStride_lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpStride_lineEdit_1.setObjectName("maxpStride_lineEdit_1")
        self.cnn_horizontalLayout_10.addWidget(self.maxpStride_lineEdit_1, 0, QtCore.Qt.AlignHCenter)
        self.maxpStridex_label = QtWidgets.QLabel(self.cnn_page)
        self.maxpStridex_label.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpStridex_label.setMaximumSize(QtCore.QSize(25, 22))
        self.maxpStridex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpStridex_label.setObjectName("maxpStridex_label")
        self.cnn_horizontalLayout_10.addWidget(self.maxpStridex_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.maxpStride_lineEdit_2 = QtWidgets.QLineEdit(self.cnn_page)
        self.maxpStride_lineEdit_2.setMinimumSize(QtCore.QSize(22, 22))
        self.maxpStride_lineEdit_2.setMaximumSize(QtCore.QSize(30, 22))
        self.maxpStride_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.maxpStride_lineEdit_2.setObjectName("maxpStride_lineEdit_2")
        self.cnn_horizontalLayout_10.addWidget(self.maxpStride_lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.cnn_verticalLayout_6.addLayout(self.cnn_horizontalLayout_10)
        self.cnn_horizontalLayout_3.addLayout(self.cnn_verticalLayout_6)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_3)
        self.cnn_line_8 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_8.setObjectName("cnn_line_8")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_8)
        self.cnn_horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_11.setObjectName("cnn_horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_11.addItem(spacerItem2)
        self.cnnPadding_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnPadding_label.setMinimumSize(QtCore.QSize(55, 22))
        self.cnnPadding_label.setMaximumSize(QtCore.QSize(70, 25))
        self.cnnPadding_label.setObjectName("cnnPadding_label")
        self.cnn_horizontalLayout_11.addWidget(self.cnnPadding_label)
        self.cnnPadding_comboBox = QtWidgets.QComboBox(self.cnn_page)
        self.cnnPadding_comboBox.setMinimumSize(QtCore.QSize(110, 22))
        self.cnnPadding_comboBox.setMaximumSize(QtCore.QSize(150, 25))
        self.cnnPadding_comboBox.setObjectName("cnnPadding_comboBox")
        self.cnnPadding_comboBox.addItem("")
        self.cnnPadding_comboBox.addItem("")
        self.cnnPadding_comboBox.addItem("")
        self.cnn_horizontalLayout_11.addWidget(self.cnnPadding_comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_11.addItem(spacerItem3)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_11)
        self.cnn_line_4 = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_4.setObjectName("cnn_line_4")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_4)
        self.cnn_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_4.setObjectName("cnn_horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_4.addItem(spacerItem4)
        self.cnnInitializer_label = QtWidgets.QLabel(self.cnn_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cnnInitializer_label.sizePolicy().hasHeightForWidth())
        self.cnnInitializer_label.setSizePolicy(sizePolicy)
        self.cnnInitializer_label.setMinimumSize(QtCore.QSize(55, 22))
        self.cnnInitializer_label.setMaximumSize(QtCore.QSize(70, 25))
        self.cnnInitializer_label.setObjectName("cnnInitializer_label")
        self.cnn_horizontalLayout_4.addWidget(self.cnnInitializer_label)
        self.cnnInitializer_comboBox = QtWidgets.QComboBox(self.cnn_page)
        self.cnnInitializer_comboBox.setMinimumSize(QtCore.QSize(110, 22))
        self.cnnInitializer_comboBox.setMaximumSize(QtCore.QSize(150, 25))
        self.cnnInitializer_comboBox.setMaxVisibleItems(14)
        self.cnnInitializer_comboBox.setObjectName("cnnInitializer_comboBox")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnnInitializer_comboBox.addItem("")
        self.cnn_horizontalLayout_4.addWidget(self.cnnInitializer_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_4.addItem(spacerItem5)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_4)
        self.cnn_line_5_ = QtWidgets.QFrame(self.cnn_page)
        self.cnn_line_5_.setFrameShape(QtWidgets.QFrame.HLine)
        self.cnn_line_5_.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cnn_line_5_.setObjectName("cnn_line_5_")
        self.cnn_verticalLayout_1.addWidget(self.cnn_line_5_)
        self.cnn_horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_5.setObjectName("cnn_horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_5.addItem(spacerItem6)
        self.cnnActivation_label = QtWidgets.QLabel(self.cnn_page)
        self.cnnActivation_label.setMinimumSize(QtCore.QSize(55, 22))
        self.cnnActivation_label.setMaximumSize(QtCore.QSize(70, 25))
        self.cnnActivation_label.setObjectName("cnnActivation_label")
        self.cnn_horizontalLayout_5.addWidget(self.cnnActivation_label)
        self.cnnActivation_comboBox = QtWidgets.QComboBox(self.cnn_page)
        self.cnnActivation_comboBox.setMinimumSize(QtCore.QSize(110, 22))
        self.cnnActivation_comboBox.setMaximumSize(QtCore.QSize(150, 25))
        self.cnnActivation_comboBox.setObjectName("cnnActivation_comboBox")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnnActivation_comboBox.addItem("")
        self.cnn_horizontalLayout_5.addWidget(self.cnnActivation_comboBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cnn_horizontalLayout_5.addItem(spacerItem7)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_5)
        self.cnn_horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.cnn_horizontalLayout_6.setObjectName("cnn_horizontalLayout_6")
        self.back_pushButton = QtWidgets.QPushButton(self.cnn_page)
        self.back_pushButton.setObjectName("back_pushButton")
        self.cnn_horizontalLayout_6.addWidget(self.back_pushButton)
        self.next_pushButton = QtWidgets.QPushButton(self.cnn_page)
        self.next_pushButton.setObjectName("next_pushButton")
        self.cnn_horizontalLayout_6.addWidget(self.next_pushButton)
        self.cnn_verticalLayout_1.addLayout(self.cnn_horizontalLayout_6)
        self.cnn_gridLayout.addLayout(self.cnn_verticalLayout_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.cnn_page)
        self.dense_page = QtWidgets.QWidget()
        self.dense_page.setObjectName("dense_page")
        self.dense_gridLayout = QtWidgets.QGridLayout(self.dense_page)
        self.dense_gridLayout.setObjectName("dense_gridLayout")
        self.dense_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.dense_verticalLayout_1.setSpacing(10)
        self.dense_verticalLayout_1.setObjectName("dense_verticalLayout_1")
        self.dense_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.dense_verticalLayout_2.setObjectName("dense_verticalLayout_2")
        self.denseName_label = QtWidgets.QLabel(self.dense_page)
        self.denseName_label.setObjectName("denseName_label")
        self.dense_verticalLayout_2.addWidget(self.denseName_label, 0, QtCore.Qt.AlignHCenter)
        self.denseName_lineEdit = QtWidgets.QLineEdit(self.dense_page)
        self.denseName_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.denseName_lineEdit.setMaximumSize(QtCore.QSize(125, 22))
        self.denseName_lineEdit.setText("")
        self.denseName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.denseName_lineEdit.setObjectName("denseName_lineEdit")
        self.dense_verticalLayout_2.addWidget(self.denseName_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.dense_verticalLayout_1.addLayout(self.dense_verticalLayout_2)
        self.dense_line_1 = QtWidgets.QFrame(self.dense_page)
        self.dense_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.dense_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dense_line_1.setObjectName("dense_line_1")
        self.dense_verticalLayout_1.addWidget(self.dense_line_1)
        self.dense_horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.dense_horizontalLayout_1.setObjectName("dense_horizontalLayout_1")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_1.addItem(spacerItem8)
        self.denseUnits_label = QtWidgets.QLabel(self.dense_page)
        self.denseUnits_label.setMinimumSize(QtCore.QSize(50, 22))
        self.denseUnits_label.setMaximumSize(QtCore.QSize(70, 25))
        self.denseUnits_label.setObjectName("denseUnits_label")
        self.dense_horizontalLayout_1.addWidget(self.denseUnits_label)
        self.denseUnits_lineEdit = QtWidgets.QLineEdit(self.dense_page)
        self.denseUnits_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.denseUnits_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.denseUnits_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.denseUnits_lineEdit.setObjectName("denseUnits_lineEdit")
        self.dense_horizontalLayout_1.addWidget(self.denseUnits_lineEdit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_1.addItem(spacerItem9)
        self.dense_verticalLayout_1.addLayout(self.dense_horizontalLayout_1)
        self.dense_line_2 = QtWidgets.QFrame(self.dense_page)
        self.dense_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.dense_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dense_line_2.setObjectName("dense_line_2")
        self.dense_verticalLayout_1.addWidget(self.dense_line_2)
        self.dense_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.dense_horizontalLayout_2.setObjectName("dense_horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_2.addItem(spacerItem10)
        self.denseDropout_label = QtWidgets.QLabel(self.dense_page)
        self.denseDropout_label.setMinimumSize(QtCore.QSize(50, 22))
        self.denseDropout_label.setMaximumSize(QtCore.QSize(70, 25))
        self.denseDropout_label.setObjectName("denseDropout_label")
        self.dense_horizontalLayout_2.addWidget(self.denseDropout_label)
        self.denseDropout_lineEdit = QtWidgets.QLineEdit(self.dense_page)
        self.denseDropout_lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.denseDropout_lineEdit.setMaximumSize(QtCore.QSize(30, 22))
        self.denseDropout_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.denseDropout_lineEdit.setObjectName("denseDropout_lineEdit")
        self.dense_horizontalLayout_2.addWidget(self.denseDropout_lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_2.addItem(spacerItem11)
        self.dense_verticalLayout_1.addLayout(self.dense_horizontalLayout_2)
        self.dense_line_3 = QtWidgets.QFrame(self.dense_page)
        self.dense_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.dense_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dense_line_3.setObjectName("dense_line_3")
        self.dense_verticalLayout_1.addWidget(self.dense_line_3)
        self.dense_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.dense_horizontalLayout_3.setObjectName("dense_horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_3.addItem(spacerItem12)
        self.denseInitializer_label = QtWidgets.QLabel(self.dense_page)
        self.denseInitializer_label.setMinimumSize(QtCore.QSize(55, 22))
        self.denseInitializer_label.setMaximumSize(QtCore.QSize(70, 25))
        self.denseInitializer_label.setObjectName("denseInitializer_label")
        self.dense_horizontalLayout_3.addWidget(self.denseInitializer_label)
        self.denseInitializer_comboBox = QtWidgets.QComboBox(self.dense_page)
        self.denseInitializer_comboBox.setMinimumSize(QtCore.QSize(110, 22))
        self.denseInitializer_comboBox.setObjectName("denseInitializer_comboBox")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.denseInitializer_comboBox.addItem("")
        self.dense_horizontalLayout_3.addWidget(self.denseInitializer_comboBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_3.addItem(spacerItem13)
        self.dense_verticalLayout_1.addLayout(self.dense_horizontalLayout_3)
        self.dense_line_4 = QtWidgets.QFrame(self.dense_page)
        self.dense_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.dense_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dense_line_4.setObjectName("dense_line_4")
        self.dense_verticalLayout_1.addWidget(self.dense_line_4)
        self.dense_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.dense_horizontalLayout_4.setObjectName("dense_horizontalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_4.addItem(spacerItem14)
        self.denseActivation_label = QtWidgets.QLabel(self.dense_page)
        self.denseActivation_label.setMinimumSize(QtCore.QSize(55, 22))
        self.denseActivation_label.setMaximumSize(QtCore.QSize(70, 25))
        self.denseActivation_label.setObjectName("denseActivation_label")
        self.dense_horizontalLayout_4.addWidget(self.denseActivation_label)
        self.denseActivation_comboBox = QtWidgets.QComboBox(self.dense_page)
        self.denseActivation_comboBox.setMinimumSize(QtCore.QSize(110, 22))
        self.denseActivation_comboBox.setObjectName("denseActivation_comboBox")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.denseActivation_comboBox.addItem("")
        self.dense_horizontalLayout_4.addWidget(self.denseActivation_comboBox)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dense_horizontalLayout_4.addItem(spacerItem15)
        self.dense_verticalLayout_1.addLayout(self.dense_horizontalLayout_4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.dense_verticalLayout_1.addItem(spacerItem16)
        self.dense_horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.dense_horizontalLayout_5.setObjectName("dense_horizontalLayout_5")
        self.back_pushButton_2 = QtWidgets.QPushButton(self.dense_page)
        self.back_pushButton_2.setObjectName("back_pushButton_2")
        self.dense_horizontalLayout_5.addWidget(self.back_pushButton_2)
        self.next_pushButton_2 = QtWidgets.QPushButton(self.dense_page)
        self.next_pushButton_2.setObjectName("next_pushButton_2")
        self.dense_horizontalLayout_5.addWidget(self.next_pushButton_2)
        self.dense_verticalLayout_1.addLayout(self.dense_horizontalLayout_5)
        self.dense_gridLayout.addLayout(self.dense_verticalLayout_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dense_page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 219, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.cnnPadding_comboBox.setCurrentIndex(0)
        self.cnnInitializer_comboBox.setCurrentIndex(0)
        self.cnnActivation_comboBox.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelName_label.setText(_translate("MainWindow", "Model\'s Name"))
        self.modelName_lineEdit.setText(_translate("MainWindow", "Gesture_Model"))
        self.cnn_label.setText(_translate("MainWindow", "CNN layers"))
        self.cnn_lineEdit.setText(_translate("MainWindow", "0"))
        self.inputSize_label.setText(_translate("MainWindow", "Input Size"))
        self.height_label.setText(_translate("MainWindow", "H:"))
        self.height_lineEdit.setText(_translate("MainWindow", "0"))
        self.width_label.setText(_translate("MainWindow", "W:"))
        self.width_lineEdit.setText(_translate("MainWindow", "0"))
        self.channels_label.setText(_translate("MainWindow", "C:"))
        self.channels_lineEdit.setText(_translate("MainWindow", "0"))
        self.dense_label.setText(_translate("MainWindow", "Dense layers"))
        self.dense_lineEdit.setText(_translate("MainWindow", "0"))
        self.classes_label.setText(_translate("MainWindow", "Classes"))
        self.classes_lineEdit.setText(_translate("MainWindow", "0"))
        self.lstm_label.setText(_translate("MainWindow", "LSTM layers"))
        self.lstm_lineEdit.setText(_translate("MainWindow", "0"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.initialize_pushButton.setText(_translate("MainWindow", "Initialize"))
        self.cnnName_label.setText(_translate("MainWindow", "CNN_layer_1 Name"))
        self.filters_label.setText(_translate("MainWindow", "Filters"))
        self.filters_lineEdit.setText(_translate("MainWindow", "0"))
        self.cnnKernel_label.setText(_translate("MainWindow", "CNN Kernel"))
        self.cnnKernel_lineEdit_1.setText(_translate("MainWindow", "0"))
        self.cnnKernelx_label.setText(_translate("MainWindow", "x"))
        self.cnnKernel_lineEdit_2.setText(_translate("MainWindow", "0"))
        self.cnnStride_label.setText(_translate("MainWindow", "CNN Stride"))
        self.cnnStride_lineEdit_1.setText(_translate("MainWindow", "0"))
        self.cnnStridex_label.setText(_translate("MainWindow", "x"))
        self.cnnStride_lineEdit_2.setText(_translate("MainWindow", "0"))
        self.maxpKernel_label.setText(_translate("MainWindow", "MaxP Kernel"))
        self.maxpKernel_lineEdit_1.setText(_translate("MainWindow", "0"))
        self.maxpKernelx_label.setText(_translate("MainWindow", "x"))
        self.maxpKernel_lineEdit_2.setText(_translate("MainWindow", "0"))
        self.maxpStride_label.setText(_translate("MainWindow", "MaxP Stride"))
        self.maxpStride_lineEdit_1.setText(_translate("MainWindow", "0"))
        self.maxpStridex_label.setText(_translate("MainWindow", "x"))
        self.maxpStride_lineEdit_2.setText(_translate("MainWindow", "0"))
        self.cnnPadding_label.setText(_translate("MainWindow", "Padding"))
        self.cnnPadding_comboBox.setItemText(0, _translate("MainWindow", "Valid"))
        self.cnnPadding_comboBox.setItemText(1, _translate("MainWindow", "Casual"))
        self.cnnPadding_comboBox.setItemText(2, _translate("MainWindow", "Same"))
        self.cnnInitializer_label.setText(_translate("MainWindow", "Initializer"))
        self.cnnInitializer_comboBox.setItemText(0, _translate("MainWindow", "Zeros"))
        self.cnnInitializer_comboBox.setItemText(1, _translate("MainWindow", "Ones"))
        self.cnnInitializer_comboBox.setItemText(2, _translate("MainWindow", "Constant"))
        self.cnnInitializer_comboBox.setItemText(3, _translate("MainWindow", "RandomNormal"))
        self.cnnInitializer_comboBox.setItemText(4, _translate("MainWindow", "RandomUniform"))
        self.cnnInitializer_comboBox.setItemText(5, _translate("MainWindow", "TruncatedNormal"))
        self.cnnInitializer_comboBox.setItemText(6, _translate("MainWindow", "VarianceScaling"))
        self.cnnInitializer_comboBox.setItemText(7, _translate("MainWindow", "Orthogonal"))
        self.cnnInitializer_comboBox.setItemText(8, _translate("MainWindow", "Identity"))
        self.cnnInitializer_comboBox.setItemText(9, _translate("MainWindow", "Glorot_Normal"))
        self.cnnInitializer_comboBox.setItemText(10, _translate("MainWindow", "Glorot_Uniform"))
        self.cnnInitializer_comboBox.setItemText(11, _translate("MainWindow", "He_Normal"))
        self.cnnInitializer_comboBox.setItemText(12, _translate("MainWindow", "He_Uniform"))
        self.cnnInitializer_comboBox.setItemText(13, _translate("MainWindow", "Lecun_Normal"))
        self.cnnInitializer_comboBox.setItemText(14, _translate("MainWindow", "Lecun_Uniform"))
        self.cnnActivation_label.setText(_translate("MainWindow", "Activation"))
        self.cnnActivation_comboBox.setItemText(0, _translate("MainWindow", "SoftMax"))
        self.cnnActivation_comboBox.setItemText(1, _translate("MainWindow", "ReLU"))
        self.cnnActivation_comboBox.setItemText(2, _translate("MainWindow", "ELU"))
        self.cnnActivation_comboBox.setItemText(3, _translate("MainWindow", "SELU"))
        self.cnnActivation_comboBox.setItemText(4, _translate("MainWindow", "SoftPlus"))
        self.cnnActivation_comboBox.setItemText(5, _translate("MainWindow", "SoftSign"))
        self.cnnActivation_comboBox.setItemText(6, _translate("MainWindow", "tanh"))
        self.cnnActivation_comboBox.setItemText(7, _translate("MainWindow", "Sigmoid"))
        self.cnnActivation_comboBox.setItemText(8, _translate("MainWindow", "Hard Sigmoid"))
        self.cnnActivation_comboBox.setItemText(9, _translate("MainWindow", "Linear"))
        self.back_pushButton.setText(_translate("MainWindow", "Back"))
        self.next_pushButton.setText(_translate("MainWindow", "Next"))
        self.denseName_label.setText(_translate("MainWindow", "Dense_layer_1 Name"))
        self.denseUnits_label.setText(_translate("MainWindow", "Units"))
        self.denseUnits_lineEdit.setText(_translate("MainWindow", "0"))
        self.denseDropout_label.setText(_translate("MainWindow", "DropOut"))
        self.denseDropout_lineEdit.setText(_translate("MainWindow", "0"))
        self.denseInitializer_label.setText(_translate("MainWindow", "Initializer"))
        self.denseInitializer_comboBox.setItemText(0, _translate("MainWindow", "Zeros"))
        self.denseInitializer_comboBox.setItemText(1, _translate("MainWindow", "Ones"))
        self.denseInitializer_comboBox.setItemText(2, _translate("MainWindow", "Constant"))
        self.denseInitializer_comboBox.setItemText(3, _translate("MainWindow", "RandomNormal"))
        self.denseInitializer_comboBox.setItemText(4, _translate("MainWindow", "RandomUniform"))
        self.denseInitializer_comboBox.setItemText(5, _translate("MainWindow", "TruncatedNormal"))
        self.denseInitializer_comboBox.setItemText(6, _translate("MainWindow", "VarianceScaling"))
        self.denseInitializer_comboBox.setItemText(7, _translate("MainWindow", "Orthogonal"))
        self.denseInitializer_comboBox.setItemText(8, _translate("MainWindow", "Identity"))
        self.denseInitializer_comboBox.setItemText(9, _translate("MainWindow", "Glorot Normal"))
        self.denseInitializer_comboBox.setItemText(10, _translate("MainWindow", "Glorot Uniform"))
        self.denseInitializer_comboBox.setItemText(11, _translate("MainWindow", "He Normal"))
        self.denseInitializer_comboBox.setItemText(12, _translate("MainWindow", "He Uniform"))
        self.denseInitializer_comboBox.setItemText(13, _translate("MainWindow", "Lecun Normal"))
        self.denseActivation_label.setText(_translate("MainWindow", "Activation"))
        self.denseActivation_comboBox.setItemText(0, _translate("MainWindow", "SoftMax"))
        self.denseActivation_comboBox.setItemText(1, _translate("MainWindow", "ReLU"))
        self.denseActivation_comboBox.setItemText(2, _translate("MainWindow", "ELU"))
        self.denseActivation_comboBox.setItemText(3, _translate("MainWindow", "SELU"))
        self.denseActivation_comboBox.setItemText(4, _translate("MainWindow", "SoftPlus"))
        self.denseActivation_comboBox.setItemText(5, _translate("MainWindow", "SoftSign"))
        self.denseActivation_comboBox.setItemText(6, _translate("MainWindow", "tanh"))
        self.denseActivation_comboBox.setItemText(7, _translate("MainWindow", "Sigmoid"))
        self.denseActivation_comboBox.setItemText(8, _translate("MainWindow", "Hard Sigmoid"))
        self.denseActivation_comboBox.setItemText(9, _translate("MainWindow", "Linear"))
        self.back_pushButton_2.setText(_translate("MainWindow", "Back"))
        self.next_pushButton_2.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

